// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Example.proto

package com.lvl6.proto.tutorial;

public final class ExampleProto {
  private ExampleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExampleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required int32 id = 2;
    boolean hasId();
    int getId();
    
    // optional string email = 3;
    boolean hasEmail();
    String getEmail();
    
    // repeated .tutorial.Example.PhoneNumber phone = 4;
    java.util.List<com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber> 
        getPhoneList();
    com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber getPhone(int index);
    int getPhoneCount();
    java.util.List<? extends com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumberOrBuilder> 
        getPhoneOrBuilderList();
    com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumberOrBuilder getPhoneOrBuilder(
        int index);
  }
  public static final class Example extends
      com.google.protobuf.GeneratedMessage
      implements ExampleOrBuilder {
    // Use Example.newBuilder() to construct.
    private Example(Builder builder) {
      super(builder);
    }
    private Example(boolean noInit) {}
    
    private static final Example defaultInstance;
    public static Example getDefaultInstance() {
      return defaultInstance;
    }
    
    public Example getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.tutorial.ExampleProto.internal_static_tutorial_Example_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.tutorial.ExampleProto.internal_static_tutorial_Example_fieldAccessorTable;
    }
    
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      MOBILE(0, 0),
      HOME(1, 1),
      WORK(2, 2),
      ;
      
      public static final int MOBILE_VALUE = 0;
      public static final int HOME_VALUE = 1;
      public static final int WORK_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static PhoneType valueOf(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.proto.tutorial.ExampleProto.Example.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final PhoneType[] VALUES = {
        MOBILE, HOME, WORK, 
      };
      
      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private PhoneType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:tutorial.Example.PhoneType)
    }
    
    public interface PhoneNumberOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string number = 1;
      boolean hasNumber();
      String getNumber();
      
      // optional .tutorial.Example.PhoneType type = 2 [default = HOME];
      boolean hasType();
      com.lvl6.proto.tutorial.ExampleProto.Example.PhoneType getType();
    }
    public static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessage
        implements PhoneNumberOrBuilder {
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber(Builder builder) {
        super(builder);
      }
      private PhoneNumber(boolean noInit) {}
      
      private static final PhoneNumber defaultInstance;
      public static PhoneNumber getDefaultInstance() {
        return defaultInstance;
      }
      
      public PhoneNumber getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.tutorial.ExampleProto.internal_static_tutorial_Example_PhoneNumber_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.tutorial.ExampleProto.internal_static_tutorial_Example_PhoneNumber_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string number = 1;
      public static final int NUMBER_FIELD_NUMBER = 1;
      private java.lang.Object number_;
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNumber() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            number_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional .tutorial.Example.PhoneType type = 2 [default = HOME];
      public static final int TYPE_FIELD_NUMBER = 2;
      private com.lvl6.proto.tutorial.ExampleProto.Example.PhoneType type_;
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.lvl6.proto.tutorial.ExampleProto.Example.PhoneType getType() {
        return type_;
      }
      
      private void initFields() {
        number_ = "";
        type_ = com.lvl6.proto.tutorial.ExampleProto.Example.PhoneType.HOME;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.lvl6.proto.tutorial.ExampleProto.internal_static_tutorial_Example_PhoneNumber_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.lvl6.proto.tutorial.ExampleProto.internal_static_tutorial_Example_PhoneNumber_fieldAccessorTable;
        }
        
        // Construct using com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          number_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = com.lvl6.proto.tutorial.ExampleProto.Example.PhoneType.HOME;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.getDescriptor();
        }
        
        public com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber getDefaultInstanceForType() {
          return com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.getDefaultInstance();
        }
        
        public com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber build() {
          com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber buildPartial() {
          com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber result = new com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.number_ = number_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber) {
            return mergeFrom((com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber other) {
          if (other == com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.getDefaultInstance()) return this;
          if (other.hasNumber()) {
            setNumber(other.getNumber());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasNumber()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                number_ = input.readBytes();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                com.lvl6.proto.tutorial.ExampleProto.Example.PhoneType value = com.lvl6.proto.tutorial.ExampleProto.Example.PhoneType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = value;
                }
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string number = 1;
        private java.lang.Object number_ = "";
        public boolean hasNumber() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getNumber() {
          java.lang.Object ref = number_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            number_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setNumber(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          number_ = value;
          onChanged();
          return this;
        }
        public Builder clearNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }
        void setNumber(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          number_ = value;
          onChanged();
        }
        
        // optional .tutorial.Example.PhoneType type = 2 [default = HOME];
        private com.lvl6.proto.tutorial.ExampleProto.Example.PhoneType type_ = com.lvl6.proto.tutorial.ExampleProto.Example.PhoneType.HOME;
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public com.lvl6.proto.tutorial.ExampleProto.Example.PhoneType getType() {
          return type_;
        }
        public Builder setType(com.lvl6.proto.tutorial.ExampleProto.Example.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = com.lvl6.proto.tutorial.ExampleProto.Example.PhoneType.HOME;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:tutorial.Example.PhoneNumber)
      }
      
      static {
        defaultInstance = new PhoneNumber(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:tutorial.Example.PhoneNumber)
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getId() {
      return id_;
    }
    
    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          email_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .tutorial.Example.PhoneNumber phone = 4;
    public static final int PHONE_FIELD_NUMBER = 4;
    private java.util.List<com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber> phone_;
    public java.util.List<com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber> getPhoneList() {
      return phone_;
    }
    public java.util.List<? extends com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumberOrBuilder> 
        getPhoneOrBuilderList() {
      return phone_;
    }
    public int getPhoneCount() {
      return phone_.size();
    }
    public com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber getPhone(int index) {
      return phone_.get(index);
    }
    public com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumberOrBuilder getPhoneOrBuilder(
        int index) {
      return phone_.get(index);
    }
    
    private void initFields() {
      name_ = "";
      id_ = 0;
      email_ = "";
      phone_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPhoneCount(); i++) {
        if (!getPhone(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      for (int i = 0; i < phone_.size(); i++) {
        output.writeMessage(4, phone_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      for (int i = 0; i < phone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, phone_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.proto.tutorial.ExampleProto.Example parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.Example parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.Example parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.Example parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.Example parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.Example parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.Example parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.tutorial.ExampleProto.Example parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.tutorial.ExampleProto.Example parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.Example parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.tutorial.ExampleProto.Example prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.proto.tutorial.ExampleProto.ExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.tutorial.ExampleProto.internal_static_tutorial_Example_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.tutorial.ExampleProto.internal_static_tutorial_Example_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.proto.tutorial.ExampleProto.Example.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPhoneFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.tutorial.ExampleProto.Example.getDescriptor();
      }
      
      public com.lvl6.proto.tutorial.ExampleProto.Example getDefaultInstanceForType() {
        return com.lvl6.proto.tutorial.ExampleProto.Example.getDefaultInstance();
      }
      
      public com.lvl6.proto.tutorial.ExampleProto.Example build() {
        com.lvl6.proto.tutorial.ExampleProto.Example result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.proto.tutorial.ExampleProto.Example buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.proto.tutorial.ExampleProto.Example result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.proto.tutorial.ExampleProto.Example buildPartial() {
        com.lvl6.proto.tutorial.ExampleProto.Example result = new com.lvl6.proto.tutorial.ExampleProto.Example(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (phoneBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            phone_ = java.util.Collections.unmodifiableList(phone_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.phone_ = phone_;
        } else {
          result.phone_ = phoneBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.tutorial.ExampleProto.Example) {
          return mergeFrom((com.lvl6.proto.tutorial.ExampleProto.Example)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.tutorial.ExampleProto.Example other) {
        if (other == com.lvl6.proto.tutorial.ExampleProto.Example.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (phoneBuilder_ == null) {
          if (!other.phone_.isEmpty()) {
            if (phone_.isEmpty()) {
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensurePhoneIsMutable();
              phone_.addAll(other.phone_);
            }
            onChanged();
          }
        } else {
          if (!other.phone_.isEmpty()) {
            if (phoneBuilder_.isEmpty()) {
              phoneBuilder_.dispose();
              phoneBuilder_ = null;
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000008);
              phoneBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPhoneFieldBuilder() : null;
            } else {
              phoneBuilder_.addAllMessages(other.phone_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getPhoneCount(); i++) {
          if (!getPhone(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 34: {
              com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.Builder subBuilder = com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPhone(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required int32 id = 2;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // optional string email = 3;
      private java.lang.Object email_ = "";
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      void setEmail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
      }
      
      // repeated .tutorial.Example.PhoneNumber phone = 4;
      private java.util.List<com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber> phone_ =
        java.util.Collections.emptyList();
      private void ensurePhoneIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          phone_ = new java.util.ArrayList<com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber>(phone_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber, com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.Builder, com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumberOrBuilder> phoneBuilder_;
      
      public java.util.List<com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber> getPhoneList() {
        if (phoneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phone_);
        } else {
          return phoneBuilder_.getMessageList();
        }
      }
      public int getPhoneCount() {
        if (phoneBuilder_ == null) {
          return phone_.size();
        } else {
          return phoneBuilder_.getCount();
        }
      }
      public com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber getPhone(int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);
        } else {
          return phoneBuilder_.getMessage(index);
        }
      }
      public Builder setPhone(
          int index, com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.set(index, value);
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPhone(
          int index, com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPhone(com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPhone(
          int index, com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(index, value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPhone(
          com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPhone(
          int index, com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPhone(
          java.lang.Iterable<? extends com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber> values) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          super.addAll(values, phone_);
          onChanged();
        } else {
          phoneBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPhone() {
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }
      public Builder removePhone(int index) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.remove(index);
          onChanged();
        } else {
          phoneBuilder_.remove(index);
        }
        return this;
      }
      public com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.Builder getPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().getBuilder(index);
      }
      public com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumberOrBuilder getPhoneOrBuilder(
          int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);  } else {
          return phoneBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumberOrBuilder> 
           getPhoneOrBuilderList() {
        if (phoneBuilder_ != null) {
          return phoneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phone_);
        }
      }
      public com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.Builder addPhoneBuilder() {
        return getPhoneFieldBuilder().addBuilder(
            com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.getDefaultInstance());
      }
      public com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.Builder addPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().addBuilder(
            index, com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.getDefaultInstance());
      }
      public java.util.List<com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.Builder> 
           getPhoneBuilderList() {
        return getPhoneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber, com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.Builder, com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumberOrBuilder> 
          getPhoneFieldBuilder() {
        if (phoneBuilder_ == null) {
          phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber, com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.Builder, com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumberOrBuilder>(
                  phone_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          phone_ = null;
        }
        return phoneBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.Example)
    }
    
    static {
      defaultInstance = new Example(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.Example)
  }
  
  public interface ExampleListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .tutorial.Example example = 1;
    java.util.List<com.lvl6.proto.tutorial.ExampleProto.Example> 
        getExampleList();
    com.lvl6.proto.tutorial.ExampleProto.Example getExample(int index);
    int getExampleCount();
    java.util.List<? extends com.lvl6.proto.tutorial.ExampleProto.ExampleOrBuilder> 
        getExampleOrBuilderList();
    com.lvl6.proto.tutorial.ExampleProto.ExampleOrBuilder getExampleOrBuilder(
        int index);
  }
  public static final class ExampleList extends
      com.google.protobuf.GeneratedMessage
      implements ExampleListOrBuilder {
    // Use ExampleList.newBuilder() to construct.
    private ExampleList(Builder builder) {
      super(builder);
    }
    private ExampleList(boolean noInit) {}
    
    private static final ExampleList defaultInstance;
    public static ExampleList getDefaultInstance() {
      return defaultInstance;
    }
    
    public ExampleList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.proto.tutorial.ExampleProto.internal_static_tutorial_ExampleList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.proto.tutorial.ExampleProto.internal_static_tutorial_ExampleList_fieldAccessorTable;
    }
    
    // repeated .tutorial.Example example = 1;
    public static final int EXAMPLE_FIELD_NUMBER = 1;
    private java.util.List<com.lvl6.proto.tutorial.ExampleProto.Example> example_;
    public java.util.List<com.lvl6.proto.tutorial.ExampleProto.Example> getExampleList() {
      return example_;
    }
    public java.util.List<? extends com.lvl6.proto.tutorial.ExampleProto.ExampleOrBuilder> 
        getExampleOrBuilderList() {
      return example_;
    }
    public int getExampleCount() {
      return example_.size();
    }
    public com.lvl6.proto.tutorial.ExampleProto.Example getExample(int index) {
      return example_.get(index);
    }
    public com.lvl6.proto.tutorial.ExampleProto.ExampleOrBuilder getExampleOrBuilder(
        int index) {
      return example_.get(index);
    }
    
    private void initFields() {
      example_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getExampleCount(); i++) {
        if (!getExample(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < example_.size(); i++) {
        output.writeMessage(1, example_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < example_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, example_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.proto.tutorial.ExampleProto.ExampleList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.ExampleList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.ExampleList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.ExampleList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.ExampleList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.ExampleList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.ExampleList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.tutorial.ExampleProto.ExampleList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.proto.tutorial.ExampleProto.ExampleList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.proto.tutorial.ExampleProto.ExampleList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.proto.tutorial.ExampleProto.ExampleList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.proto.tutorial.ExampleProto.ExampleListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.proto.tutorial.ExampleProto.internal_static_tutorial_ExampleList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.proto.tutorial.ExampleProto.internal_static_tutorial_ExampleList_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.proto.tutorial.ExampleProto.ExampleList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExampleFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (exampleBuilder_ == null) {
          example_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          exampleBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.proto.tutorial.ExampleProto.ExampleList.getDescriptor();
      }
      
      public com.lvl6.proto.tutorial.ExampleProto.ExampleList getDefaultInstanceForType() {
        return com.lvl6.proto.tutorial.ExampleProto.ExampleList.getDefaultInstance();
      }
      
      public com.lvl6.proto.tutorial.ExampleProto.ExampleList build() {
        com.lvl6.proto.tutorial.ExampleProto.ExampleList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.proto.tutorial.ExampleProto.ExampleList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.proto.tutorial.ExampleProto.ExampleList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.proto.tutorial.ExampleProto.ExampleList buildPartial() {
        com.lvl6.proto.tutorial.ExampleProto.ExampleList result = new com.lvl6.proto.tutorial.ExampleProto.ExampleList(this);
        int from_bitField0_ = bitField0_;
        if (exampleBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            example_ = java.util.Collections.unmodifiableList(example_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.example_ = example_;
        } else {
          result.example_ = exampleBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.proto.tutorial.ExampleProto.ExampleList) {
          return mergeFrom((com.lvl6.proto.tutorial.ExampleProto.ExampleList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.proto.tutorial.ExampleProto.ExampleList other) {
        if (other == com.lvl6.proto.tutorial.ExampleProto.ExampleList.getDefaultInstance()) return this;
        if (exampleBuilder_ == null) {
          if (!other.example_.isEmpty()) {
            if (example_.isEmpty()) {
              example_ = other.example_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureExampleIsMutable();
              example_.addAll(other.example_);
            }
            onChanged();
          }
        } else {
          if (!other.example_.isEmpty()) {
            if (exampleBuilder_.isEmpty()) {
              exampleBuilder_.dispose();
              exampleBuilder_ = null;
              example_ = other.example_;
              bitField0_ = (bitField0_ & ~0x00000001);
              exampleBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getExampleFieldBuilder() : null;
            } else {
              exampleBuilder_.addAllMessages(other.example_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getExampleCount(); i++) {
          if (!getExample(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.proto.tutorial.ExampleProto.Example.Builder subBuilder = com.lvl6.proto.tutorial.ExampleProto.Example.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addExample(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .tutorial.Example example = 1;
      private java.util.List<com.lvl6.proto.tutorial.ExampleProto.Example> example_ =
        java.util.Collections.emptyList();
      private void ensureExampleIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          example_ = new java.util.ArrayList<com.lvl6.proto.tutorial.ExampleProto.Example>(example_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.proto.tutorial.ExampleProto.Example, com.lvl6.proto.tutorial.ExampleProto.Example.Builder, com.lvl6.proto.tutorial.ExampleProto.ExampleOrBuilder> exampleBuilder_;
      
      public java.util.List<com.lvl6.proto.tutorial.ExampleProto.Example> getExampleList() {
        if (exampleBuilder_ == null) {
          return java.util.Collections.unmodifiableList(example_);
        } else {
          return exampleBuilder_.getMessageList();
        }
      }
      public int getExampleCount() {
        if (exampleBuilder_ == null) {
          return example_.size();
        } else {
          return exampleBuilder_.getCount();
        }
      }
      public com.lvl6.proto.tutorial.ExampleProto.Example getExample(int index) {
        if (exampleBuilder_ == null) {
          return example_.get(index);
        } else {
          return exampleBuilder_.getMessage(index);
        }
      }
      public Builder setExample(
          int index, com.lvl6.proto.tutorial.ExampleProto.Example value) {
        if (exampleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExampleIsMutable();
          example_.set(index, value);
          onChanged();
        } else {
          exampleBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setExample(
          int index, com.lvl6.proto.tutorial.ExampleProto.Example.Builder builderForValue) {
        if (exampleBuilder_ == null) {
          ensureExampleIsMutable();
          example_.set(index, builderForValue.build());
          onChanged();
        } else {
          exampleBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addExample(com.lvl6.proto.tutorial.ExampleProto.Example value) {
        if (exampleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExampleIsMutable();
          example_.add(value);
          onChanged();
        } else {
          exampleBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addExample(
          int index, com.lvl6.proto.tutorial.ExampleProto.Example value) {
        if (exampleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExampleIsMutable();
          example_.add(index, value);
          onChanged();
        } else {
          exampleBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addExample(
          com.lvl6.proto.tutorial.ExampleProto.Example.Builder builderForValue) {
        if (exampleBuilder_ == null) {
          ensureExampleIsMutable();
          example_.add(builderForValue.build());
          onChanged();
        } else {
          exampleBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addExample(
          int index, com.lvl6.proto.tutorial.ExampleProto.Example.Builder builderForValue) {
        if (exampleBuilder_ == null) {
          ensureExampleIsMutable();
          example_.add(index, builderForValue.build());
          onChanged();
        } else {
          exampleBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllExample(
          java.lang.Iterable<? extends com.lvl6.proto.tutorial.ExampleProto.Example> values) {
        if (exampleBuilder_ == null) {
          ensureExampleIsMutable();
          super.addAll(values, example_);
          onChanged();
        } else {
          exampleBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearExample() {
        if (exampleBuilder_ == null) {
          example_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          exampleBuilder_.clear();
        }
        return this;
      }
      public Builder removeExample(int index) {
        if (exampleBuilder_ == null) {
          ensureExampleIsMutable();
          example_.remove(index);
          onChanged();
        } else {
          exampleBuilder_.remove(index);
        }
        return this;
      }
      public com.lvl6.proto.tutorial.ExampleProto.Example.Builder getExampleBuilder(
          int index) {
        return getExampleFieldBuilder().getBuilder(index);
      }
      public com.lvl6.proto.tutorial.ExampleProto.ExampleOrBuilder getExampleOrBuilder(
          int index) {
        if (exampleBuilder_ == null) {
          return example_.get(index);  } else {
          return exampleBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.lvl6.proto.tutorial.ExampleProto.ExampleOrBuilder> 
           getExampleOrBuilderList() {
        if (exampleBuilder_ != null) {
          return exampleBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(example_);
        }
      }
      public com.lvl6.proto.tutorial.ExampleProto.Example.Builder addExampleBuilder() {
        return getExampleFieldBuilder().addBuilder(
            com.lvl6.proto.tutorial.ExampleProto.Example.getDefaultInstance());
      }
      public com.lvl6.proto.tutorial.ExampleProto.Example.Builder addExampleBuilder(
          int index) {
        return getExampleFieldBuilder().addBuilder(
            index, com.lvl6.proto.tutorial.ExampleProto.Example.getDefaultInstance());
      }
      public java.util.List<com.lvl6.proto.tutorial.ExampleProto.Example.Builder> 
           getExampleBuilderList() {
        return getExampleFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.proto.tutorial.ExampleProto.Example, com.lvl6.proto.tutorial.ExampleProto.Example.Builder, com.lvl6.proto.tutorial.ExampleProto.ExampleOrBuilder> 
          getExampleFieldBuilder() {
        if (exampleBuilder_ == null) {
          exampleBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lvl6.proto.tutorial.ExampleProto.Example, com.lvl6.proto.tutorial.ExampleProto.Example.Builder, com.lvl6.proto.tutorial.ExampleProto.ExampleOrBuilder>(
                  example_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          example_ = null;
        }
        return exampleBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.ExampleList)
    }
    
    static {
      defaultInstance = new ExampleList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.ExampleList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Example_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Example_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Example_PhoneNumber_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Example_PhoneNumber_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ExampleList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_ExampleList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rExample.proto\022\010tutorial\"\335\001\n\007Example\022\014\n" +
      "\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\r\n\005email\030\003 \001(\t\022," +
      "\n\005phone\030\004 \003(\0132\035.tutorial.Example.PhoneNu" +
      "mber\032N\n\013PhoneNumber\022\016\n\006number\030\001 \002(\t\022/\n\004t" +
      "ype\030\002 \001(\0162\033.tutorial.Example.PhoneType:\004" +
      "HOME\"+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022" +
      "\010\n\004WORK\020\002\"1\n\013ExampleList\022\"\n\007example\030\001 \003(" +
      "\0132\021.tutorial.ExampleB\'\n\027com.lvl6.proto.t" +
      "utorialB\014ExampleProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Example_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Example_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Example_descriptor,
              new java.lang.String[] { "Name", "Id", "Email", "Phone", },
              com.lvl6.proto.tutorial.ExampleProto.Example.class,
              com.lvl6.proto.tutorial.ExampleProto.Example.Builder.class);
          internal_static_tutorial_Example_PhoneNumber_descriptor =
            internal_static_tutorial_Example_descriptor.getNestedTypes().get(0);
          internal_static_tutorial_Example_PhoneNumber_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Example_PhoneNumber_descriptor,
              new java.lang.String[] { "Number", "Type", },
              com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.class,
              com.lvl6.proto.tutorial.ExampleProto.Example.PhoneNumber.Builder.class);
          internal_static_tutorial_ExampleList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tutorial_ExampleList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_ExampleList_descriptor,
              new java.lang.String[] { "Example", },
              com.lvl6.proto.tutorial.ExampleProto.ExampleList.class,
              com.lvl6.proto.tutorial.ExampleProto.ExampleList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
