// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginRequestEvent.proto

package com.lvl6.gamesuite.common.eventprotos;

public final class LoginRequestEventProto {
  private LoginRequestEventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginRequestEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string udid = 1;
    boolean hasUdid();
    String getUdid();
    
    // optional string loginToken = 2;
    boolean hasLoginToken();
    String getLoginToken();
    
    // optional int64 tokenExpirationDate = 3;
    boolean hasTokenExpirationDate();
    long getTokenExpirationDate();
    
    // optional string facebookId = 4;
    boolean hasFacebookId();
    String getFacebookId();
    
    // optional string name = 5;
    boolean hasName();
    String getName();
    
    // optional string password = 6;
    boolean hasPassword();
    String getPassword();
    
    // repeated string facebookFriendIds = 7;
    java.util.List<String> getFacebookFriendIdsList();
    int getFacebookFriendIdsCount();
    String getFacebookFriendIds(int index);
  }
  public static final class LoginRequestEvent extends
      com.google.protobuf.GeneratedMessage
      implements LoginRequestEventOrBuilder {
    // Use LoginRequestEvent.newBuilder() to construct.
    private LoginRequestEvent(Builder builder) {
      super(builder);
    }
    private LoginRequestEvent(boolean noInit) {}
    
    private static final LoginRequestEvent defaultInstance;
    public static LoginRequestEvent getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginRequestEvent getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.internal_static_proto_LoginRequestEvent_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.internal_static_proto_LoginRequestEvent_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string udid = 1;
    public static final int UDID_FIELD_NUMBER = 1;
    private java.lang.Object udid_;
    public boolean hasUdid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUdid() {
      java.lang.Object ref = udid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          udid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUdidBytes() {
      java.lang.Object ref = udid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        udid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string loginToken = 2;
    public static final int LOGINTOKEN_FIELD_NUMBER = 2;
    private java.lang.Object loginToken_;
    public boolean hasLoginToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLoginToken() {
      java.lang.Object ref = loginToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          loginToken_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLoginTokenBytes() {
      java.lang.Object ref = loginToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        loginToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 tokenExpirationDate = 3;
    public static final int TOKENEXPIRATIONDATE_FIELD_NUMBER = 3;
    private long tokenExpirationDate_;
    public boolean hasTokenExpirationDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getTokenExpirationDate() {
      return tokenExpirationDate_;
    }
    
    // optional string facebookId = 4;
    public static final int FACEBOOKID_FIELD_NUMBER = 4;
    private java.lang.Object facebookId_;
    public boolean hasFacebookId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getFacebookId() {
      java.lang.Object ref = facebookId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          facebookId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFacebookIdBytes() {
      java.lang.Object ref = facebookId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        facebookId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 5;
    public static final int NAME_FIELD_NUMBER = 5;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string password = 6;
    public static final int PASSWORD_FIELD_NUMBER = 6;
    private java.lang.Object password_;
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string facebookFriendIds = 7;
    public static final int FACEBOOKFRIENDIDS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList facebookFriendIds_;
    public java.util.List<String>
        getFacebookFriendIdsList() {
      return facebookFriendIds_;
    }
    public int getFacebookFriendIdsCount() {
      return facebookFriendIds_.size();
    }
    public String getFacebookFriendIds(int index) {
      return facebookFriendIds_.get(index);
    }
    
    private void initFields() {
      udid_ = "";
      loginToken_ = "";
      tokenExpirationDate_ = 0L;
      facebookId_ = "";
      name_ = "";
      password_ = "";
      facebookFriendIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUdidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLoginTokenBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, tokenExpirationDate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFacebookIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getPasswordBytes());
      }
      for (int i = 0; i < facebookFriendIds_.size(); i++) {
        output.writeBytes(7, facebookFriendIds_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUdidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLoginTokenBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, tokenExpirationDate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFacebookIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPasswordBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < facebookFriendIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(facebookFriendIds_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFacebookFriendIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.internal_static_proto_LoginRequestEvent_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.internal_static_proto_LoginRequestEvent_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        udid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        loginToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        tokenExpirationDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        facebookId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        facebookFriendIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent.getDescriptor();
      }
      
      public com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent getDefaultInstanceForType() {
        return com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent.getDefaultInstance();
      }
      
      public com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent build() {
        com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent buildPartial() {
        com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent result = new com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.udid_ = udid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.loginToken_ = loginToken_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tokenExpirationDate_ = tokenExpirationDate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.facebookId_ = facebookId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.password_ = password_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          facebookFriendIds_ = new com.google.protobuf.UnmodifiableLazyStringList(
              facebookFriendIds_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.facebookFriendIds_ = facebookFriendIds_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent) {
          return mergeFrom((com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent other) {
        if (other == com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent.getDefaultInstance()) return this;
        if (other.hasUdid()) {
          setUdid(other.getUdid());
        }
        if (other.hasLoginToken()) {
          setLoginToken(other.getLoginToken());
        }
        if (other.hasTokenExpirationDate()) {
          setTokenExpirationDate(other.getTokenExpirationDate());
        }
        if (other.hasFacebookId()) {
          setFacebookId(other.getFacebookId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (!other.facebookFriendIds_.isEmpty()) {
          if (facebookFriendIds_.isEmpty()) {
            facebookFriendIds_ = other.facebookFriendIds_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureFacebookFriendIdsIsMutable();
            facebookFriendIds_.addAll(other.facebookFriendIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              udid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              loginToken_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              tokenExpirationDate_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              facebookId_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              name_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              password_ = input.readBytes();
              break;
            }
            case 58: {
              ensureFacebookFriendIdsIsMutable();
              facebookFriendIds_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string udid = 1;
      private java.lang.Object udid_ = "";
      public boolean hasUdid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUdid() {
        java.lang.Object ref = udid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          udid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUdid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        udid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUdid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        udid_ = getDefaultInstance().getUdid();
        onChanged();
        return this;
      }
      void setUdid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        udid_ = value;
        onChanged();
      }
      
      // optional string loginToken = 2;
      private java.lang.Object loginToken_ = "";
      public boolean hasLoginToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLoginToken() {
        java.lang.Object ref = loginToken_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          loginToken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLoginToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        loginToken_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoginToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        loginToken_ = getDefaultInstance().getLoginToken();
        onChanged();
        return this;
      }
      void setLoginToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        loginToken_ = value;
        onChanged();
      }
      
      // optional int64 tokenExpirationDate = 3;
      private long tokenExpirationDate_ ;
      public boolean hasTokenExpirationDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getTokenExpirationDate() {
        return tokenExpirationDate_;
      }
      public Builder setTokenExpirationDate(long value) {
        bitField0_ |= 0x00000004;
        tokenExpirationDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearTokenExpirationDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tokenExpirationDate_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string facebookId = 4;
      private java.lang.Object facebookId_ = "";
      public boolean hasFacebookId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getFacebookId() {
        java.lang.Object ref = facebookId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          facebookId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFacebookId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        facebookId_ = value;
        onChanged();
        return this;
      }
      public Builder clearFacebookId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        facebookId_ = getDefaultInstance().getFacebookId();
        onChanged();
        return this;
      }
      void setFacebookId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        facebookId_ = value;
        onChanged();
      }
      
      // optional string name = 5;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
      }
      
      // optional string password = 6;
      private java.lang.Object password_ = "";
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        password_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000020);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        password_ = value;
        onChanged();
      }
      
      // repeated string facebookFriendIds = 7;
      private com.google.protobuf.LazyStringList facebookFriendIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFacebookFriendIdsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          facebookFriendIds_ = new com.google.protobuf.LazyStringArrayList(facebookFriendIds_);
          bitField0_ |= 0x00000040;
         }
      }
      public java.util.List<String>
          getFacebookFriendIdsList() {
        return java.util.Collections.unmodifiableList(facebookFriendIds_);
      }
      public int getFacebookFriendIdsCount() {
        return facebookFriendIds_.size();
      }
      public String getFacebookFriendIds(int index) {
        return facebookFriendIds_.get(index);
      }
      public Builder setFacebookFriendIds(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFacebookFriendIdsIsMutable();
        facebookFriendIds_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addFacebookFriendIds(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFacebookFriendIdsIsMutable();
        facebookFriendIds_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllFacebookFriendIds(
          java.lang.Iterable<String> values) {
        ensureFacebookFriendIdsIsMutable();
        super.addAll(values, facebookFriendIds_);
        onChanged();
        return this;
      }
      public Builder clearFacebookFriendIds() {
        facebookFriendIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      void addFacebookFriendIds(com.google.protobuf.ByteString value) {
        ensureFacebookFriendIdsIsMutable();
        facebookFriendIds_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:proto.LoginRequestEvent)
    }
    
    static {
      defaultInstance = new LoginRequestEvent(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.LoginRequestEvent)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_LoginRequestEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_LoginRequestEvent_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027LoginRequestEvent.proto\022\005proto\"\241\001\n\021Log" +
      "inRequestEvent\022\014\n\004udid\030\001 \001(\t\022\022\n\nloginTok" +
      "en\030\002 \001(\t\022\033\n\023tokenExpirationDate\030\003 \001(\003\022\022\n" +
      "\nfacebookId\030\004 \001(\t\022\014\n\004name\030\005 \001(\t\022\020\n\010passw" +
      "ord\030\006 \001(\t\022\031\n\021facebookFriendIds\030\007 \003(\tB?\n%" +
      "com.lvl6.gamesuite.common.eventprotosB\026L" +
      "oginRequestEventProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_LoginRequestEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_LoginRequestEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_LoginRequestEvent_descriptor,
              new java.lang.String[] { "Udid", "LoginToken", "TokenExpirationDate", "FacebookId", "Name", "Password", "FacebookFriendIds", },
              com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent.class,
              com.lvl6.gamesuite.common.eventprotos.LoginRequestEventProto.LoginRequestEvent.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
