// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginResponseEvent.proto

package com.lvl6.pictures.eventprotos;

public final class LoginResponseEventProto {
  private LoginResponseEventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginResponseEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .proto.CompleteUserProto sender = 1;
    boolean hasSender();
    com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto getSender();
    com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProtoOrBuilder getSenderOrBuilder();
    
    // repeated .proto.GameResultsProto completedGames = 2;
    java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto> 
        getCompletedGamesList();
    com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto getCompletedGames(int index);
    int getCompletedGamesCount();
    java.util.List<? extends com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProtoOrBuilder> 
        getCompletedGamesOrBuilderList();
    com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProtoOrBuilder getCompletedGamesOrBuilder(
        int index);
    
    // repeated .proto.OngoingGameProto myTurn = 3;
    java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto> 
        getMyTurnList();
    com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto getMyTurn(int index);
    int getMyTurnCount();
    java.util.List<? extends com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder> 
        getMyTurnOrBuilderList();
    com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder getMyTurnOrBuilder(
        int index);
    
    // repeated .proto.OngoingGameProto notMyTurn = 4;
    java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto> 
        getNotMyTurnList();
    com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto getNotMyTurn(int index);
    int getNotMyTurnCount();
    java.util.List<? extends com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder> 
        getNotMyTurnOrBuilderList();
    com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder getNotMyTurnOrBuilder(
        int index);
    
    // repeated .proto.QuestionProto newQuestions = 5;
    java.util.List<com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto> 
        getNewQuestionsList();
    com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto getNewQuestions(int index);
    int getNewQuestionsCount();
    java.util.List<? extends com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProtoOrBuilder> 
        getNewQuestionsOrBuilderList();
    com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProtoOrBuilder getNewQuestionsOrBuilder(
        int index);
    
    // optional .proto.LoginResponseEvent.LoginResponseStatus status = 6;
    boolean hasStatus();
    com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.LoginResponseStatus getStatus();
  }
  public static final class LoginResponseEvent extends
      com.google.protobuf.GeneratedMessage
      implements LoginResponseEventOrBuilder {
    // Use LoginResponseEvent.newBuilder() to construct.
    private LoginResponseEvent(Builder builder) {
      super(builder);
    }
    private LoginResponseEvent(boolean noInit) {}
    
    private static final LoginResponseEvent defaultInstance;
    public static LoginResponseEvent getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginResponseEvent getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.pictures.eventprotos.LoginResponseEventProto.internal_static_proto_LoginResponseEvent_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.pictures.eventprotos.LoginResponseEventProto.internal_static_proto_LoginResponseEvent_fieldAccessorTable;
    }
    
    public enum LoginResponseStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      SUCCESS_LOGIN_TOKEN(0, 0),
      SUCCESS_FACEBOOK_ID(1, 1),
      SUCCESS_NAME_PASSWORD(2, 2),
      INVALID_LOGIN_TOKEN(3, 3),
      INVALID_FACEBOOK_ID(4, 4),
      INVALID_NAME_PASSWORD(5, 5),
      ;
      
      public static final int SUCCESS_LOGIN_TOKEN_VALUE = 0;
      public static final int SUCCESS_FACEBOOK_ID_VALUE = 1;
      public static final int SUCCESS_NAME_PASSWORD_VALUE = 2;
      public static final int INVALID_LOGIN_TOKEN_VALUE = 3;
      public static final int INVALID_FACEBOOK_ID_VALUE = 4;
      public static final int INVALID_NAME_PASSWORD_VALUE = 5;
      
      
      public final int getNumber() { return value; }
      
      public static LoginResponseStatus valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS_LOGIN_TOKEN;
          case 1: return SUCCESS_FACEBOOK_ID;
          case 2: return SUCCESS_NAME_PASSWORD;
          case 3: return INVALID_LOGIN_TOKEN;
          case 4: return INVALID_FACEBOOK_ID;
          case 5: return INVALID_NAME_PASSWORD;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<LoginResponseStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<LoginResponseStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LoginResponseStatus>() {
              public LoginResponseStatus findValueByNumber(int number) {
                return LoginResponseStatus.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final LoginResponseStatus[] VALUES = {
        SUCCESS_LOGIN_TOKEN, SUCCESS_FACEBOOK_ID, SUCCESS_NAME_PASSWORD, INVALID_LOGIN_TOKEN, INVALID_FACEBOOK_ID, INVALID_NAME_PASSWORD, 
      };
      
      public static LoginResponseStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private LoginResponseStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:proto.LoginResponseEvent.LoginResponseStatus)
    }
    
    private int bitField0_;
    // optional .proto.CompleteUserProto sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto sender_;
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto getSender() {
      return sender_;
    }
    public com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProtoOrBuilder getSenderOrBuilder() {
      return sender_;
    }
    
    // repeated .proto.GameResultsProto completedGames = 2;
    public static final int COMPLETEDGAMES_FIELD_NUMBER = 2;
    private java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto> completedGames_;
    public java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto> getCompletedGamesList() {
      return completedGames_;
    }
    public java.util.List<? extends com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProtoOrBuilder> 
        getCompletedGamesOrBuilderList() {
      return completedGames_;
    }
    public int getCompletedGamesCount() {
      return completedGames_.size();
    }
    public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto getCompletedGames(int index) {
      return completedGames_.get(index);
    }
    public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProtoOrBuilder getCompletedGamesOrBuilder(
        int index) {
      return completedGames_.get(index);
    }
    
    // repeated .proto.OngoingGameProto myTurn = 3;
    public static final int MYTURN_FIELD_NUMBER = 3;
    private java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto> myTurn_;
    public java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto> getMyTurnList() {
      return myTurn_;
    }
    public java.util.List<? extends com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder> 
        getMyTurnOrBuilderList() {
      return myTurn_;
    }
    public int getMyTurnCount() {
      return myTurn_.size();
    }
    public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto getMyTurn(int index) {
      return myTurn_.get(index);
    }
    public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder getMyTurnOrBuilder(
        int index) {
      return myTurn_.get(index);
    }
    
    // repeated .proto.OngoingGameProto notMyTurn = 4;
    public static final int NOTMYTURN_FIELD_NUMBER = 4;
    private java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto> notMyTurn_;
    public java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto> getNotMyTurnList() {
      return notMyTurn_;
    }
    public java.util.List<? extends com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder> 
        getNotMyTurnOrBuilderList() {
      return notMyTurn_;
    }
    public int getNotMyTurnCount() {
      return notMyTurn_.size();
    }
    public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto getNotMyTurn(int index) {
      return notMyTurn_.get(index);
    }
    public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder getNotMyTurnOrBuilder(
        int index) {
      return notMyTurn_.get(index);
    }
    
    // repeated .proto.QuestionProto newQuestions = 5;
    public static final int NEWQUESTIONS_FIELD_NUMBER = 5;
    private java.util.List<com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto> newQuestions_;
    public java.util.List<com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto> getNewQuestionsList() {
      return newQuestions_;
    }
    public java.util.List<? extends com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProtoOrBuilder> 
        getNewQuestionsOrBuilderList() {
      return newQuestions_;
    }
    public int getNewQuestionsCount() {
      return newQuestions_.size();
    }
    public com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto getNewQuestions(int index) {
      return newQuestions_.get(index);
    }
    public com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProtoOrBuilder getNewQuestionsOrBuilder(
        int index) {
      return newQuestions_.get(index);
    }
    
    // optional .proto.LoginResponseEvent.LoginResponseStatus status = 6;
    public static final int STATUS_FIELD_NUMBER = 6;
    private com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.LoginResponseStatus status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.LoginResponseStatus getStatus() {
      return status_;
    }
    
    private void initFields() {
      sender_ = com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.getDefaultInstance();
      completedGames_ = java.util.Collections.emptyList();
      myTurn_ = java.util.Collections.emptyList();
      notMyTurn_ = java.util.Collections.emptyList();
      newQuestions_ = java.util.Collections.emptyList();
      status_ = com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.LoginResponseStatus.SUCCESS_LOGIN_TOKEN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sender_);
      }
      for (int i = 0; i < completedGames_.size(); i++) {
        output.writeMessage(2, completedGames_.get(i));
      }
      for (int i = 0; i < myTurn_.size(); i++) {
        output.writeMessage(3, myTurn_.get(i));
      }
      for (int i = 0; i < notMyTurn_.size(); i++) {
        output.writeMessage(4, notMyTurn_.get(i));
      }
      for (int i = 0; i < newQuestions_.size(); i++) {
        output.writeMessage(5, newQuestions_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(6, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sender_);
      }
      for (int i = 0; i < completedGames_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, completedGames_.get(i));
      }
      for (int i = 0; i < myTurn_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, myTurn_.get(i));
      }
      for (int i = 0; i < notMyTurn_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, notMyTurn_.get(i));
      }
      for (int i = 0; i < newQuestions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, newQuestions_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.pictures.eventprotos.LoginResponseEventProto.internal_static_proto_LoginResponseEvent_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.pictures.eventprotos.LoginResponseEventProto.internal_static_proto_LoginResponseEvent_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSenderFieldBuilder();
          getCompletedGamesFieldBuilder();
          getMyTurnFieldBuilder();
          getNotMyTurnFieldBuilder();
          getNewQuestionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.getDefaultInstance();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (completedGamesBuilder_ == null) {
          completedGames_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          completedGamesBuilder_.clear();
        }
        if (myTurnBuilder_ == null) {
          myTurn_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          myTurnBuilder_.clear();
        }
        if (notMyTurnBuilder_ == null) {
          notMyTurn_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          notMyTurnBuilder_.clear();
        }
        if (newQuestionsBuilder_ == null) {
          newQuestions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          newQuestionsBuilder_.clear();
        }
        status_ = com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.LoginResponseStatus.SUCCESS_LOGIN_TOKEN;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.getDescriptor();
      }
      
      public com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent getDefaultInstanceForType() {
        return com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.getDefaultInstance();
      }
      
      public com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent build() {
        com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent buildPartial() {
        com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent result = new com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        if (completedGamesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            completedGames_ = java.util.Collections.unmodifiableList(completedGames_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.completedGames_ = completedGames_;
        } else {
          result.completedGames_ = completedGamesBuilder_.build();
        }
        if (myTurnBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            myTurn_ = java.util.Collections.unmodifiableList(myTurn_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.myTurn_ = myTurn_;
        } else {
          result.myTurn_ = myTurnBuilder_.build();
        }
        if (notMyTurnBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            notMyTurn_ = java.util.Collections.unmodifiableList(notMyTurn_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.notMyTurn_ = notMyTurn_;
        } else {
          result.notMyTurn_ = notMyTurnBuilder_.build();
        }
        if (newQuestionsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            newQuestions_ = java.util.Collections.unmodifiableList(newQuestions_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.newQuestions_ = newQuestions_;
        } else {
          result.newQuestions_ = newQuestionsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent) {
          return mergeFrom((com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent other) {
        if (other == com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (completedGamesBuilder_ == null) {
          if (!other.completedGames_.isEmpty()) {
            if (completedGames_.isEmpty()) {
              completedGames_ = other.completedGames_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCompletedGamesIsMutable();
              completedGames_.addAll(other.completedGames_);
            }
            onChanged();
          }
        } else {
          if (!other.completedGames_.isEmpty()) {
            if (completedGamesBuilder_.isEmpty()) {
              completedGamesBuilder_.dispose();
              completedGamesBuilder_ = null;
              completedGames_ = other.completedGames_;
              bitField0_ = (bitField0_ & ~0x00000002);
              completedGamesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCompletedGamesFieldBuilder() : null;
            } else {
              completedGamesBuilder_.addAllMessages(other.completedGames_);
            }
          }
        }
        if (myTurnBuilder_ == null) {
          if (!other.myTurn_.isEmpty()) {
            if (myTurn_.isEmpty()) {
              myTurn_ = other.myTurn_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMyTurnIsMutable();
              myTurn_.addAll(other.myTurn_);
            }
            onChanged();
          }
        } else {
          if (!other.myTurn_.isEmpty()) {
            if (myTurnBuilder_.isEmpty()) {
              myTurnBuilder_.dispose();
              myTurnBuilder_ = null;
              myTurn_ = other.myTurn_;
              bitField0_ = (bitField0_ & ~0x00000004);
              myTurnBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMyTurnFieldBuilder() : null;
            } else {
              myTurnBuilder_.addAllMessages(other.myTurn_);
            }
          }
        }
        if (notMyTurnBuilder_ == null) {
          if (!other.notMyTurn_.isEmpty()) {
            if (notMyTurn_.isEmpty()) {
              notMyTurn_ = other.notMyTurn_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureNotMyTurnIsMutable();
              notMyTurn_.addAll(other.notMyTurn_);
            }
            onChanged();
          }
        } else {
          if (!other.notMyTurn_.isEmpty()) {
            if (notMyTurnBuilder_.isEmpty()) {
              notMyTurnBuilder_.dispose();
              notMyTurnBuilder_ = null;
              notMyTurn_ = other.notMyTurn_;
              bitField0_ = (bitField0_ & ~0x00000008);
              notMyTurnBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNotMyTurnFieldBuilder() : null;
            } else {
              notMyTurnBuilder_.addAllMessages(other.notMyTurn_);
            }
          }
        }
        if (newQuestionsBuilder_ == null) {
          if (!other.newQuestions_.isEmpty()) {
            if (newQuestions_.isEmpty()) {
              newQuestions_ = other.newQuestions_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureNewQuestionsIsMutable();
              newQuestions_.addAll(other.newQuestions_);
            }
            onChanged();
          }
        } else {
          if (!other.newQuestions_.isEmpty()) {
            if (newQuestionsBuilder_.isEmpty()) {
              newQuestionsBuilder_.dispose();
              newQuestionsBuilder_ = null;
              newQuestions_ = other.newQuestions_;
              bitField0_ = (bitField0_ & ~0x00000010);
              newQuestionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNewQuestionsFieldBuilder() : null;
            } else {
              newQuestionsBuilder_.addAllMessages(other.newQuestions_);
            }
          }
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.Builder subBuilder = com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.newBuilder();
              if (hasSender()) {
                subBuilder.mergeFrom(getSender());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSender(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.Builder subBuilder = com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addCompletedGames(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder subBuilder = com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMyTurn(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder subBuilder = com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNotMyTurn(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.Builder subBuilder = com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNewQuestions(subBuilder.buildPartial());
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.LoginResponseStatus value = com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.LoginResponseStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                status_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .proto.CompleteUserProto sender = 1;
      private com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto sender_ = com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto, com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.Builder, com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProtoOrBuilder> senderBuilder_;
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto getSender() {
        if (senderBuilder_ == null) {
          return sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      public Builder setSender(com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setSender(
          com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeSender(com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              sender_ != com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.getDefaultInstance()) {
            sender_ =
              com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.getDefaultInstance();
          onChanged();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.Builder getSenderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      public com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProtoOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto, com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.Builder, com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProtoOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto, com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProto.Builder, com.lvl6.pictures.noneventprotos.UserProto.CompleteUserProtoOrBuilder>(
                  sender_,
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }
      
      // repeated .proto.GameResultsProto completedGames = 2;
      private java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto> completedGames_ =
        java.util.Collections.emptyList();
      private void ensureCompletedGamesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          completedGames_ = new java.util.ArrayList<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto>(completedGames_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.Builder, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProtoOrBuilder> completedGamesBuilder_;
      
      public java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto> getCompletedGamesList() {
        if (completedGamesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(completedGames_);
        } else {
          return completedGamesBuilder_.getMessageList();
        }
      }
      public int getCompletedGamesCount() {
        if (completedGamesBuilder_ == null) {
          return completedGames_.size();
        } else {
          return completedGamesBuilder_.getCount();
        }
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto getCompletedGames(int index) {
        if (completedGamesBuilder_ == null) {
          return completedGames_.get(index);
        } else {
          return completedGamesBuilder_.getMessage(index);
        }
      }
      public Builder setCompletedGames(
          int index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto value) {
        if (completedGamesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompletedGamesIsMutable();
          completedGames_.set(index, value);
          onChanged();
        } else {
          completedGamesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setCompletedGames(
          int index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.Builder builderForValue) {
        if (completedGamesBuilder_ == null) {
          ensureCompletedGamesIsMutable();
          completedGames_.set(index, builderForValue.build());
          onChanged();
        } else {
          completedGamesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addCompletedGames(com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto value) {
        if (completedGamesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompletedGamesIsMutable();
          completedGames_.add(value);
          onChanged();
        } else {
          completedGamesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addCompletedGames(
          int index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto value) {
        if (completedGamesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompletedGamesIsMutable();
          completedGames_.add(index, value);
          onChanged();
        } else {
          completedGamesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addCompletedGames(
          com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.Builder builderForValue) {
        if (completedGamesBuilder_ == null) {
          ensureCompletedGamesIsMutable();
          completedGames_.add(builderForValue.build());
          onChanged();
        } else {
          completedGamesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addCompletedGames(
          int index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.Builder builderForValue) {
        if (completedGamesBuilder_ == null) {
          ensureCompletedGamesIsMutable();
          completedGames_.add(index, builderForValue.build());
          onChanged();
        } else {
          completedGamesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllCompletedGames(
          java.lang.Iterable<? extends com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto> values) {
        if (completedGamesBuilder_ == null) {
          ensureCompletedGamesIsMutable();
          super.addAll(values, completedGames_);
          onChanged();
        } else {
          completedGamesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearCompletedGames() {
        if (completedGamesBuilder_ == null) {
          completedGames_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          completedGamesBuilder_.clear();
        }
        return this;
      }
      public Builder removeCompletedGames(int index) {
        if (completedGamesBuilder_ == null) {
          ensureCompletedGamesIsMutable();
          completedGames_.remove(index);
          onChanged();
        } else {
          completedGamesBuilder_.remove(index);
        }
        return this;
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.Builder getCompletedGamesBuilder(
          int index) {
        return getCompletedGamesFieldBuilder().getBuilder(index);
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProtoOrBuilder getCompletedGamesOrBuilder(
          int index) {
        if (completedGamesBuilder_ == null) {
          return completedGames_.get(index);  } else {
          return completedGamesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProtoOrBuilder> 
           getCompletedGamesOrBuilderList() {
        if (completedGamesBuilder_ != null) {
          return completedGamesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(completedGames_);
        }
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.Builder addCompletedGamesBuilder() {
        return getCompletedGamesFieldBuilder().addBuilder(
            com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.getDefaultInstance());
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.Builder addCompletedGamesBuilder(
          int index) {
        return getCompletedGamesFieldBuilder().addBuilder(
            index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.getDefaultInstance());
      }
      public java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.Builder> 
           getCompletedGamesBuilderList() {
        return getCompletedGamesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.Builder, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProtoOrBuilder> 
          getCompletedGamesFieldBuilder() {
        if (completedGamesBuilder_ == null) {
          completedGamesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProto.Builder, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.GameResultsProtoOrBuilder>(
                  completedGames_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          completedGames_ = null;
        }
        return completedGamesBuilder_;
      }
      
      // repeated .proto.OngoingGameProto myTurn = 3;
      private java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto> myTurn_ =
        java.util.Collections.emptyList();
      private void ensureMyTurnIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          myTurn_ = new java.util.ArrayList<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto>(myTurn_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder> myTurnBuilder_;
      
      public java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto> getMyTurnList() {
        if (myTurnBuilder_ == null) {
          return java.util.Collections.unmodifiableList(myTurn_);
        } else {
          return myTurnBuilder_.getMessageList();
        }
      }
      public int getMyTurnCount() {
        if (myTurnBuilder_ == null) {
          return myTurn_.size();
        } else {
          return myTurnBuilder_.getCount();
        }
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto getMyTurn(int index) {
        if (myTurnBuilder_ == null) {
          return myTurn_.get(index);
        } else {
          return myTurnBuilder_.getMessage(index);
        }
      }
      public Builder setMyTurn(
          int index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto value) {
        if (myTurnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMyTurnIsMutable();
          myTurn_.set(index, value);
          onChanged();
        } else {
          myTurnBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMyTurn(
          int index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder builderForValue) {
        if (myTurnBuilder_ == null) {
          ensureMyTurnIsMutable();
          myTurn_.set(index, builderForValue.build());
          onChanged();
        } else {
          myTurnBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMyTurn(com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto value) {
        if (myTurnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMyTurnIsMutable();
          myTurn_.add(value);
          onChanged();
        } else {
          myTurnBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMyTurn(
          int index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto value) {
        if (myTurnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMyTurnIsMutable();
          myTurn_.add(index, value);
          onChanged();
        } else {
          myTurnBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMyTurn(
          com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder builderForValue) {
        if (myTurnBuilder_ == null) {
          ensureMyTurnIsMutable();
          myTurn_.add(builderForValue.build());
          onChanged();
        } else {
          myTurnBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMyTurn(
          int index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder builderForValue) {
        if (myTurnBuilder_ == null) {
          ensureMyTurnIsMutable();
          myTurn_.add(index, builderForValue.build());
          onChanged();
        } else {
          myTurnBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMyTurn(
          java.lang.Iterable<? extends com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto> values) {
        if (myTurnBuilder_ == null) {
          ensureMyTurnIsMutable();
          super.addAll(values, myTurn_);
          onChanged();
        } else {
          myTurnBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMyTurn() {
        if (myTurnBuilder_ == null) {
          myTurn_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          myTurnBuilder_.clear();
        }
        return this;
      }
      public Builder removeMyTurn(int index) {
        if (myTurnBuilder_ == null) {
          ensureMyTurnIsMutable();
          myTurn_.remove(index);
          onChanged();
        } else {
          myTurnBuilder_.remove(index);
        }
        return this;
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder getMyTurnBuilder(
          int index) {
        return getMyTurnFieldBuilder().getBuilder(index);
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder getMyTurnOrBuilder(
          int index) {
        if (myTurnBuilder_ == null) {
          return myTurn_.get(index);  } else {
          return myTurnBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder> 
           getMyTurnOrBuilderList() {
        if (myTurnBuilder_ != null) {
          return myTurnBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(myTurn_);
        }
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder addMyTurnBuilder() {
        return getMyTurnFieldBuilder().addBuilder(
            com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.getDefaultInstance());
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder addMyTurnBuilder(
          int index) {
        return getMyTurnFieldBuilder().addBuilder(
            index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.getDefaultInstance());
      }
      public java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder> 
           getMyTurnBuilderList() {
        return getMyTurnFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder> 
          getMyTurnFieldBuilder() {
        if (myTurnBuilder_ == null) {
          myTurnBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder>(
                  myTurn_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          myTurn_ = null;
        }
        return myTurnBuilder_;
      }
      
      // repeated .proto.OngoingGameProto notMyTurn = 4;
      private java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto> notMyTurn_ =
        java.util.Collections.emptyList();
      private void ensureNotMyTurnIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          notMyTurn_ = new java.util.ArrayList<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto>(notMyTurn_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder> notMyTurnBuilder_;
      
      public java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto> getNotMyTurnList() {
        if (notMyTurnBuilder_ == null) {
          return java.util.Collections.unmodifiableList(notMyTurn_);
        } else {
          return notMyTurnBuilder_.getMessageList();
        }
      }
      public int getNotMyTurnCount() {
        if (notMyTurnBuilder_ == null) {
          return notMyTurn_.size();
        } else {
          return notMyTurnBuilder_.getCount();
        }
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto getNotMyTurn(int index) {
        if (notMyTurnBuilder_ == null) {
          return notMyTurn_.get(index);
        } else {
          return notMyTurnBuilder_.getMessage(index);
        }
      }
      public Builder setNotMyTurn(
          int index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto value) {
        if (notMyTurnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotMyTurnIsMutable();
          notMyTurn_.set(index, value);
          onChanged();
        } else {
          notMyTurnBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNotMyTurn(
          int index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder builderForValue) {
        if (notMyTurnBuilder_ == null) {
          ensureNotMyTurnIsMutable();
          notMyTurn_.set(index, builderForValue.build());
          onChanged();
        } else {
          notMyTurnBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNotMyTurn(com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto value) {
        if (notMyTurnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotMyTurnIsMutable();
          notMyTurn_.add(value);
          onChanged();
        } else {
          notMyTurnBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNotMyTurn(
          int index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto value) {
        if (notMyTurnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNotMyTurnIsMutable();
          notMyTurn_.add(index, value);
          onChanged();
        } else {
          notMyTurnBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNotMyTurn(
          com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder builderForValue) {
        if (notMyTurnBuilder_ == null) {
          ensureNotMyTurnIsMutable();
          notMyTurn_.add(builderForValue.build());
          onChanged();
        } else {
          notMyTurnBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNotMyTurn(
          int index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder builderForValue) {
        if (notMyTurnBuilder_ == null) {
          ensureNotMyTurnIsMutable();
          notMyTurn_.add(index, builderForValue.build());
          onChanged();
        } else {
          notMyTurnBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNotMyTurn(
          java.lang.Iterable<? extends com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto> values) {
        if (notMyTurnBuilder_ == null) {
          ensureNotMyTurnIsMutable();
          super.addAll(values, notMyTurn_);
          onChanged();
        } else {
          notMyTurnBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNotMyTurn() {
        if (notMyTurnBuilder_ == null) {
          notMyTurn_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          notMyTurnBuilder_.clear();
        }
        return this;
      }
      public Builder removeNotMyTurn(int index) {
        if (notMyTurnBuilder_ == null) {
          ensureNotMyTurnIsMutable();
          notMyTurn_.remove(index);
          onChanged();
        } else {
          notMyTurnBuilder_.remove(index);
        }
        return this;
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder getNotMyTurnBuilder(
          int index) {
        return getNotMyTurnFieldBuilder().getBuilder(index);
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder getNotMyTurnOrBuilder(
          int index) {
        if (notMyTurnBuilder_ == null) {
          return notMyTurn_.get(index);  } else {
          return notMyTurnBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder> 
           getNotMyTurnOrBuilderList() {
        if (notMyTurnBuilder_ != null) {
          return notMyTurnBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(notMyTurn_);
        }
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder addNotMyTurnBuilder() {
        return getNotMyTurnFieldBuilder().addBuilder(
            com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.getDefaultInstance());
      }
      public com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder addNotMyTurnBuilder(
          int index) {
        return getNotMyTurnFieldBuilder().addBuilder(
            index, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.getDefaultInstance());
      }
      public java.util.List<com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder> 
           getNotMyTurnBuilderList() {
        return getNotMyTurnFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder> 
          getNotMyTurnFieldBuilder() {
        if (notMyTurnBuilder_ == null) {
          notMyTurnBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProto.Builder, com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.OngoingGameProtoOrBuilder>(
                  notMyTurn_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          notMyTurn_ = null;
        }
        return notMyTurnBuilder_;
      }
      
      // repeated .proto.QuestionProto newQuestions = 5;
      private java.util.List<com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto> newQuestions_ =
        java.util.Collections.emptyList();
      private void ensureNewQuestionsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          newQuestions_ = new java.util.ArrayList<com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto>(newQuestions_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto, com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.Builder, com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProtoOrBuilder> newQuestionsBuilder_;
      
      public java.util.List<com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto> getNewQuestionsList() {
        if (newQuestionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(newQuestions_);
        } else {
          return newQuestionsBuilder_.getMessageList();
        }
      }
      public int getNewQuestionsCount() {
        if (newQuestionsBuilder_ == null) {
          return newQuestions_.size();
        } else {
          return newQuestionsBuilder_.getCount();
        }
      }
      public com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto getNewQuestions(int index) {
        if (newQuestionsBuilder_ == null) {
          return newQuestions_.get(index);
        } else {
          return newQuestionsBuilder_.getMessage(index);
        }
      }
      public Builder setNewQuestions(
          int index, com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto value) {
        if (newQuestionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewQuestionsIsMutable();
          newQuestions_.set(index, value);
          onChanged();
        } else {
          newQuestionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNewQuestions(
          int index, com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.Builder builderForValue) {
        if (newQuestionsBuilder_ == null) {
          ensureNewQuestionsIsMutable();
          newQuestions_.set(index, builderForValue.build());
          onChanged();
        } else {
          newQuestionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNewQuestions(com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto value) {
        if (newQuestionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewQuestionsIsMutable();
          newQuestions_.add(value);
          onChanged();
        } else {
          newQuestionsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNewQuestions(
          int index, com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto value) {
        if (newQuestionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewQuestionsIsMutable();
          newQuestions_.add(index, value);
          onChanged();
        } else {
          newQuestionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNewQuestions(
          com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.Builder builderForValue) {
        if (newQuestionsBuilder_ == null) {
          ensureNewQuestionsIsMutable();
          newQuestions_.add(builderForValue.build());
          onChanged();
        } else {
          newQuestionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNewQuestions(
          int index, com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.Builder builderForValue) {
        if (newQuestionsBuilder_ == null) {
          ensureNewQuestionsIsMutable();
          newQuestions_.add(index, builderForValue.build());
          onChanged();
        } else {
          newQuestionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNewQuestions(
          java.lang.Iterable<? extends com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto> values) {
        if (newQuestionsBuilder_ == null) {
          ensureNewQuestionsIsMutable();
          super.addAll(values, newQuestions_);
          onChanged();
        } else {
          newQuestionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNewQuestions() {
        if (newQuestionsBuilder_ == null) {
          newQuestions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          newQuestionsBuilder_.clear();
        }
        return this;
      }
      public Builder removeNewQuestions(int index) {
        if (newQuestionsBuilder_ == null) {
          ensureNewQuestionsIsMutable();
          newQuestions_.remove(index);
          onChanged();
        } else {
          newQuestionsBuilder_.remove(index);
        }
        return this;
      }
      public com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.Builder getNewQuestionsBuilder(
          int index) {
        return getNewQuestionsFieldBuilder().getBuilder(index);
      }
      public com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProtoOrBuilder getNewQuestionsOrBuilder(
          int index) {
        if (newQuestionsBuilder_ == null) {
          return newQuestions_.get(index);  } else {
          return newQuestionsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProtoOrBuilder> 
           getNewQuestionsOrBuilderList() {
        if (newQuestionsBuilder_ != null) {
          return newQuestionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(newQuestions_);
        }
      }
      public com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.Builder addNewQuestionsBuilder() {
        return getNewQuestionsFieldBuilder().addBuilder(
            com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.getDefaultInstance());
      }
      public com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.Builder addNewQuestionsBuilder(
          int index) {
        return getNewQuestionsFieldBuilder().addBuilder(
            index, com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.getDefaultInstance());
      }
      public java.util.List<com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.Builder> 
           getNewQuestionsBuilderList() {
        return getNewQuestionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto, com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.Builder, com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProtoOrBuilder> 
          getNewQuestionsFieldBuilder() {
        if (newQuestionsBuilder_ == null) {
          newQuestionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto, com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProto.Builder, com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.QuestionProtoOrBuilder>(
                  newQuestions_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          newQuestions_ = null;
        }
        return newQuestionsBuilder_;
      }
      
      // optional .proto.LoginResponseEvent.LoginResponseStatus status = 6;
      private com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.LoginResponseStatus status_ = com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.LoginResponseStatus.SUCCESS_LOGIN_TOKEN;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.LoginResponseStatus getStatus() {
        return status_;
      }
      public Builder setStatus(com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.LoginResponseStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.LoginResponseStatus.SUCCESS_LOGIN_TOKEN;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.LoginResponseEvent)
    }
    
    static {
      defaultInstance = new LoginResponseEvent(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.LoginResponseEvent)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_LoginResponseEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_LoginResponseEvent_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030LoginResponseEvent.proto\022\005proto\032\030Trivi" +
      "aGameOverview.proto\032\032TriviaQuestionForma" +
      "t.proto\032\022CompleteUser.proto\"\341\003\n\022LoginRes" +
      "ponseEvent\022(\n\006sender\030\001 \001(\0132\030.proto.Compl" +
      "eteUserProto\022/\n\016completedGames\030\002 \003(\0132\027.p" +
      "roto.GameResultsProto\022\'\n\006myTurn\030\003 \003(\0132\027." +
      "proto.OngoingGameProto\022*\n\tnotMyTurn\030\004 \003(" +
      "\0132\027.proto.OngoingGameProto\022*\n\014newQuestio" +
      "ns\030\005 \003(\0132\024.proto.QuestionProto\022=\n\006status" +
      "\030\006 \001(\0162-.proto.LoginResponseEvent.LoginR",
      "esponseStatus\"\257\001\n\023LoginResponseStatus\022\027\n" +
      "\023SUCCESS_LOGIN_TOKEN\020\000\022\027\n\023SUCCESS_FACEBO" +
      "OK_ID\020\001\022\031\n\025SUCCESS_NAME_PASSWORD\020\002\022\027\n\023IN" +
      "VALID_LOGIN_TOKEN\020\003\022\027\n\023INVALID_FACEBOOK_" +
      "ID\020\004\022\031\n\025INVALID_NAME_PASSWORD\020\005B8\n\035com.l" +
      "vl6.pictures.eventprotosB\027LoginResponseE" +
      "ventProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_LoginResponseEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_LoginResponseEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_LoginResponseEvent_descriptor,
              new java.lang.String[] { "Sender", "CompletedGames", "MyTurn", "NotMyTurn", "NewQuestions", "Status", },
              com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.class,
              com.lvl6.pictures.eventprotos.LoginResponseEventProto.LoginResponseEvent.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.pictures.noneventprotos.TriviaGameOverviewProto.getDescriptor(),
          com.lvl6.pictures.noneventprotos.TriviaQuestionFormatProto.getDescriptor(),
          com.lvl6.pictures.noneventprotos.UserProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
