// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchForUserEvent.proto

package com.lvl6.pictures.eventprotos;

public final class SearchForUserEventProto {
  private SearchForUserEventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SearchForUserRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .proto.BasicUserProto sender = 1;
    boolean hasSender();
    com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto getSender();
    com.lvl6.pictures.noneventprotos.UserProto.BasicUserProtoOrBuilder getSenderOrBuilder();
    
    // optional string nameOfPerson = 2;
    boolean hasNameOfPerson();
    String getNameOfPerson();
  }
  public static final class SearchForUserRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements SearchForUserRequestProtoOrBuilder {
    // Use SearchForUserRequestProto.newBuilder() to construct.
    private SearchForUserRequestProto(Builder builder) {
      super(builder);
    }
    private SearchForUserRequestProto(boolean noInit) {}
    
    private static final SearchForUserRequestProto defaultInstance;
    public static SearchForUserRequestProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public SearchForUserRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.pictures.eventprotos.SearchForUserEventProto.internal_static_proto_SearchForUserRequestProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.pictures.eventprotos.SearchForUserEventProto.internal_static_proto_SearchForUserRequestProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .proto.BasicUserProto sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto sender_;
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto getSender() {
      return sender_;
    }
    public com.lvl6.pictures.noneventprotos.UserProto.BasicUserProtoOrBuilder getSenderOrBuilder() {
      return sender_;
    }
    
    // optional string nameOfPerson = 2;
    public static final int NAMEOFPERSON_FIELD_NUMBER = 2;
    private java.lang.Object nameOfPerson_;
    public boolean hasNameOfPerson() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getNameOfPerson() {
      java.lang.Object ref = nameOfPerson_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nameOfPerson_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameOfPersonBytes() {
      java.lang.Object ref = nameOfPerson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nameOfPerson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      sender_ = com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.getDefaultInstance();
      nameOfPerson_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameOfPersonBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sender_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameOfPersonBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.pictures.eventprotos.SearchForUserEventProto.internal_static_proto_SearchForUserRequestProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.pictures.eventprotos.SearchForUserEventProto.internal_static_proto_SearchForUserRequestProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSenderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.getDefaultInstance();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        nameOfPerson_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto.getDescriptor();
      }
      
      public com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto getDefaultInstanceForType() {
        return com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto.getDefaultInstance();
      }
      
      public com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto build() {
        com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto buildPartial() {
        com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto result = new com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (senderBuilder_ == null) {
          result.sender_ = sender_;
        } else {
          result.sender_ = senderBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nameOfPerson_ = nameOfPerson_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto) {
          return mergeFrom((com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto other) {
        if (other == com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto.getDefaultInstance()) return this;
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (other.hasNameOfPerson()) {
          setNameOfPerson(other.getNameOfPerson());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.Builder subBuilder = com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.newBuilder();
              if (hasSender()) {
                subBuilder.mergeFrom(getSender());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSender(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              nameOfPerson_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .proto.BasicUserProto sender = 1;
      private com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto sender_ = com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto, com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.Builder, com.lvl6.pictures.noneventprotos.UserProto.BasicUserProtoOrBuilder> senderBuilder_;
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto getSender() {
        if (senderBuilder_ == null) {
          return sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      public Builder setSender(com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
          onChanged();
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setSender(
          com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
          onChanged();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeSender(com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              sender_ != com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.getDefaultInstance()) {
            sender_ =
              com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.newBuilder(sender_).mergeFrom(value).buildPartial();
          } else {
            sender_ = value;
          }
          onChanged();
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearSender() {
        if (senderBuilder_ == null) {
          sender_ = com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.getDefaultInstance();
          onChanged();
        } else {
          senderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.Builder getSenderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      public com.lvl6.pictures.noneventprotos.UserProto.BasicUserProtoOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto, com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.Builder, com.lvl6.pictures.noneventprotos.UserProto.BasicUserProtoOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto, com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.Builder, com.lvl6.pictures.noneventprotos.UserProto.BasicUserProtoOrBuilder>(
                  sender_,
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }
      
      // optional string nameOfPerson = 2;
      private java.lang.Object nameOfPerson_ = "";
      public boolean hasNameOfPerson() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getNameOfPerson() {
        java.lang.Object ref = nameOfPerson_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nameOfPerson_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNameOfPerson(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nameOfPerson_ = value;
        onChanged();
        return this;
      }
      public Builder clearNameOfPerson() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nameOfPerson_ = getDefaultInstance().getNameOfPerson();
        onChanged();
        return this;
      }
      void setNameOfPerson(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        nameOfPerson_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:proto.SearchForUserRequestProto)
    }
    
    static {
      defaultInstance = new SearchForUserRequestProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.SearchForUserRequestProto)
  }
  
  public interface SearchForUserResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .proto.BasicUserProto recipient = 1;
    boolean hasRecipient();
    com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto getRecipient();
    com.lvl6.pictures.noneventprotos.UserProto.BasicUserProtoOrBuilder getRecipientOrBuilder();
    
    // optional int32 nameOfPersonId = 2;
    boolean hasNameOfPersonId();
    int getNameOfPersonId();
    
    // optional .proto.SearchForUserResponseProto.SearchForUserStatus status = 3;
    boolean hasStatus();
    com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.SearchForUserStatus getStatus();
  }
  public static final class SearchForUserResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements SearchForUserResponseProtoOrBuilder {
    // Use SearchForUserResponseProto.newBuilder() to construct.
    private SearchForUserResponseProto(Builder builder) {
      super(builder);
    }
    private SearchForUserResponseProto(boolean noInit) {}
    
    private static final SearchForUserResponseProto defaultInstance;
    public static SearchForUserResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public SearchForUserResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.pictures.eventprotos.SearchForUserEventProto.internal_static_proto_SearchForUserResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.pictures.eventprotos.SearchForUserEventProto.internal_static_proto_SearchForUserResponseProto_fieldAccessorTable;
    }
    
    public enum SearchForUserStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      SUCCESS(0, 1),
      FAIL_PERSON_NOT_FOUND(1, 2),
      FAIL_OTHER(2, 3),
      ;
      
      public static final int SUCCESS_VALUE = 1;
      public static final int FAIL_PERSON_NOT_FOUND_VALUE = 2;
      public static final int FAIL_OTHER_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static SearchForUserStatus valueOf(int value) {
        switch (value) {
          case 1: return SUCCESS;
          case 2: return FAIL_PERSON_NOT_FOUND;
          case 3: return FAIL_OTHER;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<SearchForUserStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<SearchForUserStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SearchForUserStatus>() {
              public SearchForUserStatus findValueByNumber(int number) {
                return SearchForUserStatus.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final SearchForUserStatus[] VALUES = {
        SUCCESS, FAIL_PERSON_NOT_FOUND, FAIL_OTHER, 
      };
      
      public static SearchForUserStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private SearchForUserStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:proto.SearchForUserResponseProto.SearchForUserStatus)
    }
    
    private int bitField0_;
    // optional .proto.BasicUserProto recipient = 1;
    public static final int RECIPIENT_FIELD_NUMBER = 1;
    private com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto recipient_;
    public boolean hasRecipient() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto getRecipient() {
      return recipient_;
    }
    public com.lvl6.pictures.noneventprotos.UserProto.BasicUserProtoOrBuilder getRecipientOrBuilder() {
      return recipient_;
    }
    
    // optional int32 nameOfPersonId = 2;
    public static final int NAMEOFPERSONID_FIELD_NUMBER = 2;
    private int nameOfPersonId_;
    public boolean hasNameOfPersonId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getNameOfPersonId() {
      return nameOfPersonId_;
    }
    
    // optional .proto.SearchForUserResponseProto.SearchForUserStatus status = 3;
    public static final int STATUS_FIELD_NUMBER = 3;
    private com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.SearchForUserStatus status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.SearchForUserStatus getStatus() {
      return status_;
    }
    
    private void initFields() {
      recipient_ = com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.getDefaultInstance();
      nameOfPersonId_ = 0;
      status_ = com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.SearchForUserStatus.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, recipient_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, nameOfPersonId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, recipient_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, nameOfPersonId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.pictures.eventprotos.SearchForUserEventProto.internal_static_proto_SearchForUserResponseProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.pictures.eventprotos.SearchForUserEventProto.internal_static_proto_SearchForUserResponseProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRecipientFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (recipientBuilder_ == null) {
          recipient_ = com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.getDefaultInstance();
        } else {
          recipientBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        nameOfPersonId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.SearchForUserStatus.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.getDescriptor();
      }
      
      public com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto getDefaultInstanceForType() {
        return com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.getDefaultInstance();
      }
      
      public com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto build() {
        com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto buildPartial() {
        com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto result = new com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (recipientBuilder_ == null) {
          result.recipient_ = recipient_;
        } else {
          result.recipient_ = recipientBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nameOfPersonId_ = nameOfPersonId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto) {
          return mergeFrom((com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto other) {
        if (other == com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.getDefaultInstance()) return this;
        if (other.hasRecipient()) {
          mergeRecipient(other.getRecipient());
        }
        if (other.hasNameOfPersonId()) {
          setNameOfPersonId(other.getNameOfPersonId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.Builder subBuilder = com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.newBuilder();
              if (hasRecipient()) {
                subBuilder.mergeFrom(getRecipient());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRecipient(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              nameOfPersonId_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.SearchForUserStatus value = com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.SearchForUserStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                status_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .proto.BasicUserProto recipient = 1;
      private com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto recipient_ = com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto, com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.Builder, com.lvl6.pictures.noneventprotos.UserProto.BasicUserProtoOrBuilder> recipientBuilder_;
      public boolean hasRecipient() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto getRecipient() {
        if (recipientBuilder_ == null) {
          return recipient_;
        } else {
          return recipientBuilder_.getMessage();
        }
      }
      public Builder setRecipient(com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto value) {
        if (recipientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          recipient_ = value;
          onChanged();
        } else {
          recipientBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setRecipient(
          com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.Builder builderForValue) {
        if (recipientBuilder_ == null) {
          recipient_ = builderForValue.build();
          onChanged();
        } else {
          recipientBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeRecipient(com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto value) {
        if (recipientBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              recipient_ != com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.getDefaultInstance()) {
            recipient_ =
              com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.newBuilder(recipient_).mergeFrom(value).buildPartial();
          } else {
            recipient_ = value;
          }
          onChanged();
        } else {
          recipientBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearRecipient() {
        if (recipientBuilder_ == null) {
          recipient_ = com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.getDefaultInstance();
          onChanged();
        } else {
          recipientBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.Builder getRecipientBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRecipientFieldBuilder().getBuilder();
      }
      public com.lvl6.pictures.noneventprotos.UserProto.BasicUserProtoOrBuilder getRecipientOrBuilder() {
        if (recipientBuilder_ != null) {
          return recipientBuilder_.getMessageOrBuilder();
        } else {
          return recipient_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto, com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.Builder, com.lvl6.pictures.noneventprotos.UserProto.BasicUserProtoOrBuilder> 
          getRecipientFieldBuilder() {
        if (recipientBuilder_ == null) {
          recipientBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto, com.lvl6.pictures.noneventprotos.UserProto.BasicUserProto.Builder, com.lvl6.pictures.noneventprotos.UserProto.BasicUserProtoOrBuilder>(
                  recipient_,
                  getParentForChildren(),
                  isClean());
          recipient_ = null;
        }
        return recipientBuilder_;
      }
      
      // optional int32 nameOfPersonId = 2;
      private int nameOfPersonId_ ;
      public boolean hasNameOfPersonId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getNameOfPersonId() {
        return nameOfPersonId_;
      }
      public Builder setNameOfPersonId(int value) {
        bitField0_ |= 0x00000002;
        nameOfPersonId_ = value;
        onChanged();
        return this;
      }
      public Builder clearNameOfPersonId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nameOfPersonId_ = 0;
        onChanged();
        return this;
      }
      
      // optional .proto.SearchForUserResponseProto.SearchForUserStatus status = 3;
      private com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.SearchForUserStatus status_ = com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.SearchForUserStatus.SUCCESS;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.SearchForUserStatus getStatus() {
        return status_;
      }
      public Builder setStatus(com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.SearchForUserStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.SearchForUserStatus.SUCCESS;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.SearchForUserResponseProto)
    }
    
    static {
      defaultInstance = new SearchForUserResponseProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.SearchForUserResponseProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SearchForUserRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_SearchForUserRequestProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SearchForUserResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_SearchForUserResponseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030SearchForUserEvent.proto\022\005proto\032\nUser." +
      "proto\"X\n\031SearchForUserRequestProto\022%\n\006se" +
      "nder\030\001 \001(\0132\025.proto.BasicUserProto\022\024\n\014nam" +
      "eOfPerson\030\002 \001(\t\"\364\001\n\032SearchForUserRespons" +
      "eProto\022(\n\trecipient\030\001 \001(\0132\025.proto.BasicU" +
      "serProto\022\026\n\016nameOfPersonId\030\002 \001(\005\022E\n\006stat" +
      "us\030\003 \001(\01625.proto.SearchForUserResponsePr" +
      "oto.SearchForUserStatus\"M\n\023SearchForUser" +
      "Status\022\013\n\007SUCCESS\020\001\022\031\n\025FAIL_PERSON_NOT_F" +
      "OUND\020\002\022\016\n\nFAIL_OTHER\020\003B8\n\035com.lvl6.pictu",
      "res.eventprotosB\027SearchForUserEventProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_SearchForUserRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_SearchForUserRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_SearchForUserRequestProto_descriptor,
              new java.lang.String[] { "Sender", "NameOfPerson", },
              com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto.class,
              com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserRequestProto.Builder.class);
          internal_static_proto_SearchForUserResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_SearchForUserResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_SearchForUserResponseProto_descriptor,
              new java.lang.String[] { "Recipient", "NameOfPersonId", "Status", },
              com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.class,
              com.lvl6.pictures.eventprotos.SearchForUserEventProto.SearchForUserResponseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lvl6.pictures.noneventprotos.UserProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
