// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonEventProtocol.proto

package com.lvl6.gamesuite.common.noneventprotos;

public final class CommonEventProtocolProto {
  private CommonEventProtocolProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum CommonEventProtocolRequest
      implements com.google.protobuf.ProtocolMessageEnum {
    C_CREATE_ACCOUNT_VIA_FACEBOOK_EVENT(0, 1),
    C_CREATE_ACCOUNT_VIA_EMAIL_EVENT(1, 2),
    C_CREATE_ACCOUNT_VIA_NO_CREDENTIALS(2, 3),
    ;
    
    public static final int C_CREATE_ACCOUNT_VIA_FACEBOOK_EVENT_VALUE = 1;
    public static final int C_CREATE_ACCOUNT_VIA_EMAIL_EVENT_VALUE = 2;
    public static final int C_CREATE_ACCOUNT_VIA_NO_CREDENTIALS_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static CommonEventProtocolRequest valueOf(int value) {
      switch (value) {
        case 1: return C_CREATE_ACCOUNT_VIA_FACEBOOK_EVENT;
        case 2: return C_CREATE_ACCOUNT_VIA_EMAIL_EVENT;
        case 3: return C_CREATE_ACCOUNT_VIA_NO_CREDENTIALS;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CommonEventProtocolRequest>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CommonEventProtocolRequest>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommonEventProtocolRequest>() {
            public CommonEventProtocolRequest findValueByNumber(int number) {
              return CommonEventProtocolRequest.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lvl6.gamesuite.common.noneventprotos.CommonEventProtocolProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final CommonEventProtocolRequest[] VALUES = {
      C_CREATE_ACCOUNT_VIA_FACEBOOK_EVENT, C_CREATE_ACCOUNT_VIA_EMAIL_EVENT, C_CREATE_ACCOUNT_VIA_NO_CREDENTIALS, 
    };
    
    public static CommonEventProtocolRequest valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private CommonEventProtocolRequest(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:proto.CommonEventProtocolRequest)
  }
  
  public enum CommonEventProtocolResponse
      implements com.google.protobuf.ProtocolMessageEnum {
    S_CREATE_ACCOUNT_EVENT(0, 1),
    ;
    
    public static final int S_CREATE_ACCOUNT_EVENT_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static CommonEventProtocolResponse valueOf(int value) {
      switch (value) {
        case 1: return S_CREATE_ACCOUNT_EVENT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CommonEventProtocolResponse>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CommonEventProtocolResponse>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommonEventProtocolResponse>() {
            public CommonEventProtocolResponse findValueByNumber(int number) {
              return CommonEventProtocolResponse.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lvl6.gamesuite.common.noneventprotos.CommonEventProtocolProto.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final CommonEventProtocolResponse[] VALUES = {
      S_CREATE_ACCOUNT_EVENT, 
    };
    
    public static CommonEventProtocolResponse valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private CommonEventProtocolResponse(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:proto.CommonEventProtocolResponse)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031CommonEventProtocol.proto\022\005proto*\224\001\n\032C" +
      "ommonEventProtocolRequest\022\'\n#C_CREATE_AC" +
      "COUNT_VIA_FACEBOOK_EVENT\020\001\022$\n C_CREATE_A" +
      "CCOUNT_VIA_EMAIL_EVENT\020\002\022\'\n#C_CREATE_ACC" +
      "OUNT_VIA_NO_CREDENTIALS\020\003*9\n\033CommonEvent" +
      "ProtocolResponse\022\032\n\026S_CREATE_ACCOUNT_EVE" +
      "NT\020\001BD\n(com.lvl6.gamesuite.common.noneve" +
      "ntprotosB\030CommonEventProtocolProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
