// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ForceLogout.proto

package com.lvl6.gamesuite.common.noneventprotos;

public final class ForceLogoutProto {
  private ForceLogoutProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ForceLogoutResponseProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string udid = 1;
    boolean hasUdid();
    String getUdid();
  }
  public static final class ForceLogoutResponseProto extends
      com.google.protobuf.GeneratedMessage
      implements ForceLogoutResponseProtoOrBuilder {
    // Use ForceLogoutResponseProto.newBuilder() to construct.
    private ForceLogoutResponseProto(Builder builder) {
      super(builder);
    }
    private ForceLogoutResponseProto(boolean noInit) {}
    
    private static final ForceLogoutResponseProto defaultInstance;
    public static ForceLogoutResponseProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public ForceLogoutResponseProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.internal_static_proto_ForceLogoutResponseProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.internal_static_proto_ForceLogoutResponseProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string udid = 1;
    public static final int UDID_FIELD_NUMBER = 1;
    private java.lang.Object udid_;
    public boolean hasUdid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUdid() {
      java.lang.Object ref = udid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          udid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUdidBytes() {
      java.lang.Object ref = udid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        udid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      udid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUdidBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUdidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.internal_static_proto_ForceLogoutResponseProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.internal_static_proto_ForceLogoutResponseProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        udid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto.getDescriptor();
      }
      
      public com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto getDefaultInstanceForType() {
        return com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto.getDefaultInstance();
      }
      
      public com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto build() {
        com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto buildPartial() {
        com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto result = new com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.udid_ = udid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto) {
          return mergeFrom((com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto other) {
        if (other == com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto.getDefaultInstance()) return this;
        if (other.hasUdid()) {
          setUdid(other.getUdid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              udid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string udid = 1;
      private java.lang.Object udid_ = "";
      public boolean hasUdid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUdid() {
        java.lang.Object ref = udid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          udid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUdid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        udid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUdid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        udid_ = getDefaultInstance().getUdid();
        onChanged();
        return this;
      }
      void setUdid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        udid_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:proto.ForceLogoutResponseProto)
    }
    
    static {
      defaultInstance = new ForceLogoutResponseProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.ForceLogoutResponseProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ForceLogoutResponseProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ForceLogoutResponseProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ForceLogout.proto\022\005proto\"(\n\030ForceLogou" +
      "tResponseProto\022\014\n\004udid\030\001 \001(\tB<\n(com.lvl6" +
      ".gamesuite.common.noneventprotosB\020ForceL" +
      "ogoutProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_ForceLogoutResponseProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_ForceLogoutResponseProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_ForceLogoutResponseProto_descriptor,
              new java.lang.String[] { "Udid", },
              com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto.class,
              com.lvl6.gamesuite.common.noneventprotos.ForceLogoutProto.ForceLogoutResponseProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
