// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BasicUser.proto

package com.lvl6.gamesuite.common.noneventprotos;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BasicUserProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string userId = 1;
    boolean hasUserId();
    String getUserId();
    
    // optional string nameStrangersSee = 2;
    boolean hasNameStrangersSee();
    String getNameStrangersSee();
    
    // optional string nameFriendsSee = 3;
    boolean hasNameFriendsSee();
    String getNameFriendsSee();
    
    // optional string email = 4;
    boolean hasEmail();
    String getEmail();
    
    // optional .proto.BasicAuthorizedDevice basicAuthorizedDevice = 5;
    boolean hasBasicAuthorizedDevice();
    com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice getBasicAuthorizedDevice();
    com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDeviceOrBuilder getBasicAuthorizedDeviceOrBuilder();
  }
  public static final class BasicUserProto extends
      com.google.protobuf.GeneratedMessage
      implements BasicUserProtoOrBuilder {
    // Use BasicUserProto.newBuilder() to construct.
    private BasicUserProto(Builder builder) {
      super(builder);
    }
    private BasicUserProto(boolean noInit) {}
    
    private static final BasicUserProto defaultInstance;
    public static BasicUserProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public BasicUserProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.gamesuite.common.noneventprotos.UserProto.internal_static_proto_BasicUserProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.gamesuite.common.noneventprotos.UserProto.internal_static_proto_BasicUserProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string nameStrangersSee = 2;
    public static final int NAMESTRANGERSSEE_FIELD_NUMBER = 2;
    private java.lang.Object nameStrangersSee_;
    public boolean hasNameStrangersSee() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getNameStrangersSee() {
      java.lang.Object ref = nameStrangersSee_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nameStrangersSee_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameStrangersSeeBytes() {
      java.lang.Object ref = nameStrangersSee_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nameStrangersSee_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string nameFriendsSee = 3;
    public static final int NAMEFRIENDSSEE_FIELD_NUMBER = 3;
    private java.lang.Object nameFriendsSee_;
    public boolean hasNameFriendsSee() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getNameFriendsSee() {
      java.lang.Object ref = nameFriendsSee_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nameFriendsSee_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameFriendsSeeBytes() {
      java.lang.Object ref = nameFriendsSee_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nameFriendsSee_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string email = 4;
    public static final int EMAIL_FIELD_NUMBER = 4;
    private java.lang.Object email_;
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          email_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .proto.BasicAuthorizedDevice basicAuthorizedDevice = 5;
    public static final int BASICAUTHORIZEDDEVICE_FIELD_NUMBER = 5;
    private com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice basicAuthorizedDevice_;
    public boolean hasBasicAuthorizedDevice() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice getBasicAuthorizedDevice() {
      return basicAuthorizedDevice_;
    }
    public com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDeviceOrBuilder getBasicAuthorizedDeviceOrBuilder() {
      return basicAuthorizedDevice_;
    }
    
    private void initFields() {
      userId_ = "";
      nameStrangersSee_ = "";
      nameFriendsSee_ = "";
      email_ = "";
      basicAuthorizedDevice_ = com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameStrangersSeeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameFriendsSeeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getEmailBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, basicAuthorizedDevice_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameStrangersSeeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameFriendsSeeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getEmailBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, basicAuthorizedDevice_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.gamesuite.common.noneventprotos.UserProto.internal_static_proto_BasicUserProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.gamesuite.common.noneventprotos.UserProto.internal_static_proto_BasicUserProto_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBasicAuthorizedDeviceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        nameStrangersSee_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        nameFriendsSee_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (basicAuthorizedDeviceBuilder_ == null) {
          basicAuthorizedDevice_ = com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.getDefaultInstance();
        } else {
          basicAuthorizedDeviceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto.getDescriptor();
      }
      
      public com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto getDefaultInstanceForType() {
        return com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto.getDefaultInstance();
      }
      
      public com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto build() {
        com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto buildPartial() {
        com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto result = new com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nameStrangersSee_ = nameStrangersSee_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nameFriendsSee_ = nameFriendsSee_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (basicAuthorizedDeviceBuilder_ == null) {
          result.basicAuthorizedDevice_ = basicAuthorizedDevice_;
        } else {
          result.basicAuthorizedDevice_ = basicAuthorizedDeviceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto) {
          return mergeFrom((com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto other) {
        if (other == com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasNameStrangersSee()) {
          setNameStrangersSee(other.getNameStrangersSee());
        }
        if (other.hasNameFriendsSee()) {
          setNameFriendsSee(other.getNameFriendsSee());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasBasicAuthorizedDevice()) {
          mergeBasicAuthorizedDevice(other.getBasicAuthorizedDevice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              nameStrangersSee_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              nameFriendsSee_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              email_ = input.readBytes();
              break;
            }
            case 42: {
              com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.Builder subBuilder = com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.newBuilder();
              if (hasBasicAuthorizedDevice()) {
                subBuilder.mergeFrom(getBasicAuthorizedDevice());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBasicAuthorizedDevice(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string userId = 1;
      private java.lang.Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
      }
      
      // optional string nameStrangersSee = 2;
      private java.lang.Object nameStrangersSee_ = "";
      public boolean hasNameStrangersSee() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getNameStrangersSee() {
        java.lang.Object ref = nameStrangersSee_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nameStrangersSee_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNameStrangersSee(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nameStrangersSee_ = value;
        onChanged();
        return this;
      }
      public Builder clearNameStrangersSee() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nameStrangersSee_ = getDefaultInstance().getNameStrangersSee();
        onChanged();
        return this;
      }
      void setNameStrangersSee(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        nameStrangersSee_ = value;
        onChanged();
      }
      
      // optional string nameFriendsSee = 3;
      private java.lang.Object nameFriendsSee_ = "";
      public boolean hasNameFriendsSee() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getNameFriendsSee() {
        java.lang.Object ref = nameFriendsSee_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nameFriendsSee_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNameFriendsSee(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nameFriendsSee_ = value;
        onChanged();
        return this;
      }
      public Builder clearNameFriendsSee() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nameFriendsSee_ = getDefaultInstance().getNameFriendsSee();
        onChanged();
        return this;
      }
      void setNameFriendsSee(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        nameFriendsSee_ = value;
        onChanged();
      }
      
      // optional string email = 4;
      private java.lang.Object email_ = "";
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        email_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000008);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      void setEmail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        email_ = value;
        onChanged();
      }
      
      // optional .proto.BasicAuthorizedDevice basicAuthorizedDevice = 5;
      private com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice basicAuthorizedDevice_ = com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice, com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.Builder, com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDeviceOrBuilder> basicAuthorizedDeviceBuilder_;
      public boolean hasBasicAuthorizedDevice() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice getBasicAuthorizedDevice() {
        if (basicAuthorizedDeviceBuilder_ == null) {
          return basicAuthorizedDevice_;
        } else {
          return basicAuthorizedDeviceBuilder_.getMessage();
        }
      }
      public Builder setBasicAuthorizedDevice(com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice value) {
        if (basicAuthorizedDeviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          basicAuthorizedDevice_ = value;
          onChanged();
        } else {
          basicAuthorizedDeviceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setBasicAuthorizedDevice(
          com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.Builder builderForValue) {
        if (basicAuthorizedDeviceBuilder_ == null) {
          basicAuthorizedDevice_ = builderForValue.build();
          onChanged();
        } else {
          basicAuthorizedDeviceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeBasicAuthorizedDevice(com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice value) {
        if (basicAuthorizedDeviceBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              basicAuthorizedDevice_ != com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.getDefaultInstance()) {
            basicAuthorizedDevice_ =
              com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.newBuilder(basicAuthorizedDevice_).mergeFrom(value).buildPartial();
          } else {
            basicAuthorizedDevice_ = value;
          }
          onChanged();
        } else {
          basicAuthorizedDeviceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearBasicAuthorizedDevice() {
        if (basicAuthorizedDeviceBuilder_ == null) {
          basicAuthorizedDevice_ = com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.getDefaultInstance();
          onChanged();
        } else {
          basicAuthorizedDeviceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.Builder getBasicAuthorizedDeviceBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getBasicAuthorizedDeviceFieldBuilder().getBuilder();
      }
      public com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDeviceOrBuilder getBasicAuthorizedDeviceOrBuilder() {
        if (basicAuthorizedDeviceBuilder_ != null) {
          return basicAuthorizedDeviceBuilder_.getMessageOrBuilder();
        } else {
          return basicAuthorizedDevice_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice, com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.Builder, com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDeviceOrBuilder> 
          getBasicAuthorizedDeviceFieldBuilder() {
        if (basicAuthorizedDeviceBuilder_ == null) {
          basicAuthorizedDeviceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice, com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.Builder, com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDeviceOrBuilder>(
                  basicAuthorizedDevice_,
                  getParentForChildren(),
                  isClean());
          basicAuthorizedDevice_ = null;
        }
        return basicAuthorizedDeviceBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.BasicUserProto)
    }
    
    static {
      defaultInstance = new BasicUserProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.BasicUserProto)
  }
  
  public interface BasicAuthorizedDeviceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string userId = 1;
    boolean hasUserId();
    String getUserId();
    
    // optional string loginToken = 2;
    boolean hasLoginToken();
    String getLoginToken();
    
    // optional int64 expirationDate = 3;
    boolean hasExpirationDate();
    long getExpirationDate();
    
    // optional string udid = 4;
    boolean hasUdid();
    String getUdid();
  }
  public static final class BasicAuthorizedDevice extends
      com.google.protobuf.GeneratedMessage
      implements BasicAuthorizedDeviceOrBuilder {
    // Use BasicAuthorizedDevice.newBuilder() to construct.
    private BasicAuthorizedDevice(Builder builder) {
      super(builder);
    }
    private BasicAuthorizedDevice(boolean noInit) {}
    
    private static final BasicAuthorizedDevice defaultInstance;
    public static BasicAuthorizedDevice getDefaultInstance() {
      return defaultInstance;
    }
    
    public BasicAuthorizedDevice getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lvl6.gamesuite.common.noneventprotos.UserProto.internal_static_proto_BasicAuthorizedDevice_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lvl6.gamesuite.common.noneventprotos.UserProto.internal_static_proto_BasicAuthorizedDevice_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string loginToken = 2;
    public static final int LOGINTOKEN_FIELD_NUMBER = 2;
    private java.lang.Object loginToken_;
    public boolean hasLoginToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLoginToken() {
      java.lang.Object ref = loginToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          loginToken_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLoginTokenBytes() {
      java.lang.Object ref = loginToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        loginToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 expirationDate = 3;
    public static final int EXPIRATIONDATE_FIELD_NUMBER = 3;
    private long expirationDate_;
    public boolean hasExpirationDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getExpirationDate() {
      return expirationDate_;
    }
    
    // optional string udid = 4;
    public static final int UDID_FIELD_NUMBER = 4;
    private java.lang.Object udid_;
    public boolean hasUdid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getUdid() {
      java.lang.Object ref = udid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          udid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUdidBytes() {
      java.lang.Object ref = udid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        udid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      userId_ = "";
      loginToken_ = "";
      expirationDate_ = 0L;
      udid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLoginTokenBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, expirationDate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUdidBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLoginTokenBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, expirationDate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUdidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDeviceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lvl6.gamesuite.common.noneventprotos.UserProto.internal_static_proto_BasicAuthorizedDevice_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lvl6.gamesuite.common.noneventprotos.UserProto.internal_static_proto_BasicAuthorizedDevice_fieldAccessorTable;
      }
      
      // Construct using com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        loginToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        expirationDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        udid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.getDescriptor();
      }
      
      public com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice getDefaultInstanceForType() {
        return com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.getDefaultInstance();
      }
      
      public com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice build() {
        com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice buildPartial() {
        com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice result = new com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.loginToken_ = loginToken_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.expirationDate_ = expirationDate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.udid_ = udid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice) {
          return mergeFrom((com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice other) {
        if (other == com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasLoginToken()) {
          setLoginToken(other.getLoginToken());
        }
        if (other.hasExpirationDate()) {
          setExpirationDate(other.getExpirationDate());
        }
        if (other.hasUdid()) {
          setUdid(other.getUdid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              loginToken_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              expirationDate_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              udid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string userId = 1;
      private java.lang.Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
      }
      
      // optional string loginToken = 2;
      private java.lang.Object loginToken_ = "";
      public boolean hasLoginToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLoginToken() {
        java.lang.Object ref = loginToken_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          loginToken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLoginToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        loginToken_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoginToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        loginToken_ = getDefaultInstance().getLoginToken();
        onChanged();
        return this;
      }
      void setLoginToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        loginToken_ = value;
        onChanged();
      }
      
      // optional int64 expirationDate = 3;
      private long expirationDate_ ;
      public boolean hasExpirationDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getExpirationDate() {
        return expirationDate_;
      }
      public Builder setExpirationDate(long value) {
        bitField0_ |= 0x00000004;
        expirationDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearExpirationDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        expirationDate_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string udid = 4;
      private java.lang.Object udid_ = "";
      public boolean hasUdid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getUdid() {
        java.lang.Object ref = udid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          udid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUdid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        udid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUdid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        udid_ = getDefaultInstance().getUdid();
        onChanged();
        return this;
      }
      void setUdid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        udid_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:proto.BasicAuthorizedDevice)
    }
    
    static {
      defaultInstance = new BasicAuthorizedDevice(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.BasicAuthorizedDevice)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BasicUserProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_BasicUserProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BasicAuthorizedDevice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_BasicAuthorizedDevice_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017BasicUser.proto\022\005proto\"\236\001\n\016BasicUserPr" +
      "oto\022\016\n\006userId\030\001 \001(\t\022\030\n\020nameStrangersSee\030" +
      "\002 \001(\t\022\026\n\016nameFriendsSee\030\003 \001(\t\022\r\n\005email\030\004" +
      " \001(\t\022;\n\025basicAuthorizedDevice\030\005 \001(\0132\034.pr" +
      "oto.BasicAuthorizedDevice\"a\n\025BasicAuthor" +
      "izedDevice\022\016\n\006userId\030\001 \001(\t\022\022\n\nloginToken" +
      "\030\002 \001(\t\022\026\n\016expirationDate\030\003 \001(\003\022\014\n\004udid\030\004" +
      " \001(\tB5\n(com.lvl6.gamesuite.common.noneve" +
      "ntprotosB\tUserProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_BasicUserProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_BasicUserProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_BasicUserProto_descriptor,
              new java.lang.String[] { "UserId", "NameStrangersSee", "NameFriendsSee", "Email", "BasicAuthorizedDevice", },
              com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto.class,
              com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicUserProto.Builder.class);
          internal_static_proto_BasicAuthorizedDevice_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_BasicAuthorizedDevice_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_BasicAuthorizedDevice_descriptor,
              new java.lang.String[] { "UserId", "LoginToken", "ExpirationDate", "Udid", },
              com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.class,
              com.lvl6.gamesuite.common.noneventprotos.UserProto.BasicAuthorizedDevice.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
